# Generated by Django 3.2.6 on 2021-08-06 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modify_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 6, 3, 16, 19, 852012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='write_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 6, 3, 16, 19, 827232, tzinfo=utc)),
        ),
    ]
