# Generated by Django 3.2.6 on 2021-08-06 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20210806_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modify_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 6, 4, 32, 35, 782185, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='write_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 6, 4, 32, 35, 762358, tzinfo=utc)),
        ),
    ]
